/**
 * Maho Storefront — /.well-known/api-catalog (RFC 9727)
 * Copyright (c) 2026 Mage Australia Pty Ltd
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * JSON Resource Descriptor advertising the storefront's API surface so
 * agents can discover capabilities programmatically (rather than scraping
 * documentation). The Link header on every response already points here;
 * this file is what they find.
 *
 * The actual API spec is auto-generated by Maho's API Platform on the
 * backend and served at /api/docs.json (storefront proxies it via the
 * /api/* catch-all to /api/rest/v2/...). Reference both the OpenAPI JSON
 * (machine-readable) and the HTML docs (human-readable Swagger UI).
 */

interface ApiCatalogInput {
  origin: string;
}

export function generateApiCatalog({ origin }: ApiCatalogInput): object {
  return {
    linkset: [
      {
        anchor: `${origin}/.well-known/api-catalog`,
        // Machine-readable specification.
        'service-desc': [
          {
            href: `${origin}/api/docs.json`,
            type: 'application/vnd.oai.openapi+json',
            title: 'OpenAPI 3 specification (JSON)',
          },
        ],
        // Human-readable docs.
        'service-doc': [
          {
            href: `${origin}/api/docs`,
            type: 'text/html',
            title: 'Swagger UI',
          },
        ],
        // Liveness / version probe.
        status: [
          {
            href: `${origin}/pulse`,
            type: 'application/json',
            title: 'Storefront pulse (worker hash + last-sync timestamp)',
          },
        ],
        // OAuth discovery descriptor, for authenticated agent flows.
        'authorization-server': [
          {
            href: `${origin}/.well-known/oauth-authorization-server`,
            type: 'application/json',
          },
        ],
        // MCP server, for agents that prefer the tool-calling interface.
        'mcp-server': [
          {
            href: `${origin}/.well-known/mcp/server-card.json`,
            type: 'application/json',
          },
        ],
      },
    ],
  };
}
